# Site configuration for Dark Showers Papers
title: "Dark Showers Papers - Living Review"
description: "A comprehensive collection of papers on dark showers and related BSM physics"
url: "https://ds-wg.github.io"
baseurl: "/DS_living_review"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Disable theme header navigation
header_pages: []

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections for papers
collections:
  papers:
    output: false

# Default settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Include files that would normally be excluded
include:
  - results/

# Exclude files from processing
exclude:
  - "results/README.md"
  - "results/*.json"
  - "results/*.bib"
  - "*.py"
  - "*.pyc"
  - "__pycache__"