name: Update Dark Showers Papers

on:
  schedule:
    - cron: '0 2 1 * *'  # Monthly on the 1st
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
    paths:
      - '*.py'
      - '.github/workflows/update-papers.yml'

permissions:
  contents: write

jobs:
  update-papers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib pandas numpy python-dateutil
        
    - name: Run paper generation
      run: |
        echo "Running bibliography generator..."
        python improved_inspire_bib_generator_v2.py -o results
        
    - name: Run plotting
      run: |
        echo "Running plotter..."
        python bsm_darkshowers_plotter_v1.py --single-plot -o results
        
    - name: Verify results
      run: |
        echo "Checking generated files..."
        ls -lah results/
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add results/
        git diff --staged --quiet || git commit -m "Update papers and plots $(date +'%Y-%m-%d %H:%M')"
        git push || echo "No changes to push"